---
language: python
python: "3.7"

notifications:
  email: false

# cache pre-commit to speed up builds
cache:
  directories:
    - $HOME/.cache/pre-commit

install:
  - pip install pre-commit
  - pip install tox
  - pip install flask
  - python3 -m pip install setuptools wheel

script:
  - pre-commit run --all-files
  - tox -e py37
  # packages the project and saves the names of the files into file_arr
  - python3 setup.py sdist bdist_wheel
  - file_arr=($(ls dist/))
  # installs our packaged tool
  - pip install dist/${file_arr[0]}
  # sets the Travis-CI shell width because Schemathesis needs a value for shell width
  - stty cols 80
  # starts test server and runs our tool against the server
  - python3 test/mock_server/flask_app.py &
    ibm-service-validator run
    test/mock_definitions/mock_server.yaml
    -b http://localhost:5000
    --hypothesis-phases=generate
    --statistics
    --no-additional-cases

before_deploy:
  - pip install bump2version
  - npm install npm@latest -g
  - nvm install 12
  - npm install @semantic-release/changelog
  - npm install @semantic-release/exec
  - npm install @semantic-release/git
  - npm install @semantic-release/github

deploy:
  - provider: script
    script: npx semantic-release
    skip_cleanup: true
    on:
      branch: master
  - provider: pypi
    user: $PYPI_USER
    password: $PYPI_TOKEN
    repository: https://upload.pypi.org/legacy
    skip_cleanup: true
    on:
      tags: true
