---
language: python
python: "3.7"

notifications:
  email: false

# cache pre-commit to speed up builds
cache:
  directories:
    - $HOME/.cache/pre-commit

jobs:
  include:

    - stage: linter and code formatter
      install:
        - pip install pre-commit
      script:
        - pre-commit run --all-files

    - stage: test suite
      install:
        - pip install tox
      script:
        - tox -e py37

    - stage: deploy to releases
      install:
        - python3 -m pip install setuptools wheel
      script:
        - python3 setup.py sdist bdist_wheel

      deploy:
        provider: releases
        api_key: $GH_TOKEN
        file_glob: true
        file: dist/*
        skip_cleanup: true
        on:
          tags: true
