---
language: python
python: "3.7"

notifications:
  email: false

# cache pre-commit to speed up builds
cache:
  directories:
    - $HOME/.cache/pre-commit

jobs:
  include:

    - stage: linting, code formatting, and unit tests
      install:
        - pip install pre-commit
        - pip install tox
      script:
        - pre-commit run --all-files
        - tox -e py37

      before_deploy:
        - python3 -m pip install setuptools wheel
        - python3 setup.py sdist bdist_wheel
      deploy:
        provider: releases
        api_key: $GH_TOKEN
        file_glob: true
        file: dist/*
        skip_cleanup: true
        on:
          tags: true
